# NOTE: update this with your service name
service: restaurant-meetup-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  createUser:
    handler: createUser.main
    events:
      - http:
          path: restaurant-meetup-users
          method: post
          cors: true

  createGroup:
    handler: createGroup.main
    events:
      - http:
          path: restaurant-meetup-groups
          method: post
          cors: true

  getAllGroups:
    handler: getAllGroups.main
    events:
      - http:
          path: restaurant-meetup-groups
          method: get
          cors: true

  updateGroup:
    handler: updateGroup.main
    events:
      - http:
          path: restaurant-meetup-groups
          method: put
          cors: true

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
